locals {
  job_definition_name = "${local.resource_name}-job-definition"
  main_container_name = "main"
  command             = length(var.command) > 0 ? var.command : null
  effective_image_url = local.app_version == "" ? local.image_url : "${local.image_url}:${local.app_version}"

  has_secrets = length(local.all_secret_keys) > 0

  container_resources = merge(
    {
      requests = {
        cpu    = var.cpu
        memory = var.memory
      }
    },
    (var.max_cpu != "" || var.max_memory != "") ? {
      limits = merge(
        var.max_cpu != "" ? { cpu = var.max_cpu } : {},
        var.max_memory != "" ? { memory = var.max_memory } : {},
      )
    } : {},
  )
}

// For EKS Tasks, we are going to create a job definition and emit via outputs
// Users of this app module (e.g. `nullstone exec`) can use this job definition as a template and customize to liking
// For instance, an execution may override CMD or add environment variables.
locals {
  pod_volumes = concat(
    [
      for name, v in local.volumes : {
        name                  = name
        persistentVolumeClaim = v.persistent_volume_claim
        emptyDir              = v.empty_dir
        hostPath              = v.host_path
      }
    ],
    local.has_secrets ? [
      {
        name = "secrets-store"
        csi = {
          driver   = "secrets-store.csi.k8s.io"
          readOnly = true
          volumeAttributes = {
            secretProviderClass = local.spc_name
          }
        }
      }
    ] : [],
  )

  pod_volume_mounts = concat(
    [
      for name, vm in local.volume_mounts : {
        name             = name
        mountPath        = vm.mount_path
        subPath          = vm.sub_path
        mountPropagation = vm.mount_propagation
        readOnly         = vm.read_only
        subPathExpr      = vm.sub_path_expr
      }
    ],
    local.has_secrets ? [
      {
        name      = "secrets-store"
        mountPath = "/mnt/secrets-store"
        readOnly  = true
      }
    ] : [],
  )

  pod_env_vars = [
    for k, v in local.env_vars_plain : {
      name  = k
      value = v
    }
  ]
  // env vars with "{{ k8s.field(apiVersion, fieldPath) }}"
  pod_field_refs = [
    for k, v in local.env_var_field_refs : {
      name = k
      valueFrom = {
        fieldRef = {
          apiVersion = v.api_version
          fieldPath  = v.field_path
        }
      }
    }
  ]
  // env vars with "{{ k8s.configMap(key, name[, optional]) }}"
  pod_config_map_refs = [
    for k, v in local.env_var_config_map_refs : {
      name = k
      valueFrom = {
        configMapKeyRef = {
          key      = v.key
          name     = v.name
          optional = v.optional
        }
      }
    }
  ]
  // env vars with "{{ k8s.resourceField(resource[, container, divisor]) }}"
  pod_resource_field_refs = [
    for k, v in local.env_var_resource_field_refs : {
      name = k
      valueFrom = {
        resourceFieldRef = {
          resource      = v.resource
          containerName = v.container
          divisor       = v.divisor
        }
      }
    }
  ]
  // env vars with "{{ k8s.fileKey(key, path, volumeName) }}"
  // Requires K8s 1.34+ and EnvFiles feature gate
  pod_file_key_refs = [
    for k, v in local.env_var_file_key_refs : {
      name = k
      valueFrom = {
        fileKeyRef = {
          key        = v.key
          path       = v.path
          volumeName = v.volume_name
        }
      }
    }
  ]
  pod_secrets = [
    for k in local.all_secret_keys : {
      name = k
      valueFrom = {
        secretKeyRef = {
          name = local.app_secret_store_name
          key  = k
        }
      }
    }
  ]

  job_definition = jsonencode({
    metadata = {
      namespace = local.kubernetes_namespace
      name      = "" // a unique name is generated by Nullstone when running the job
      labels    = local.app_labels
    }
    spec = {
      completions             = 1            // we only want to run 1 job
      backoffLimit            = 0            // do not retry builder jobs
      ttlSecondsAfterFinished = 24 * 60 * 60 // retain completed jobs for 1 day

      template = {
        metadata = {
          namespace = local.kubernetes_namespace
          labels    = local.app_labels
        }
        spec = {
          restartPolicy      = "Never"
          volumes            = local.pod_volumes
          serviceAccountName = kubernetes_service_account_v1.app.metadata[0].name

          containers = [
            {
              name         = local.main_container_name
              image        = local.effective_image_url
              args         = local.command
              env          = concat(local.pod_env_vars, local.pod_field_refs, local.pod_config_map_refs, local.pod_resource_field_refs, local.pod_file_key_refs, local.pod_secrets)
              volumeMounts = local.pod_volume_mounts
              resources    = local.container_resources
            }
          ]
        }
      }
    }
  })
}

resource "kubernetes_config_map_v1" "job_definition" {
  metadata {
    namespace = local.kubernetes_namespace
    name      = local.job_definition_name
    labels    = local.app_labels
  }

  data = {
    template = local.job_definition
  }
}
